name: landingpage
description: Cross platform sample landing page implemented in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.68.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any
  service_worker: ^0.2.0
  googleapis_auth: ^0.2.3+5
  provider: any
  http: 0.12.0+2
  webfeed: ^0.4.2

dev_dependencies:
  #dependencies to enable the Dart web build system
  build_runner: ^1.4.0 # ^1.3.5 (building site)
  build_web_compilers: ^2.0.0
  flutter_web_test: any
  #webfeed: any


#flutter:
#  uses-material-design: true

  ## These overrides tell the package tools to get them from GitHub
dependency_overrides:
#  http:
#    git:
#      url: https://github.com/dart-lang/http
#
#  webfeed:
#    git:
#      url: https://github.com/witochandra/webfeed
#
#  service_worker:
#    git:
#      url: https://github.com/isoos/service_worker
#
#  googleapis_auth:
#    git:
#      url: https://github.com/dart-lang/googleapis_auth

  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web

  firebase:
    git:
      url: https://github.com/FirebaseExtended/firebase-dart
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test